print("`````~~~~~~~~~~~~``````")
print("Interactive Calculator")
print("`````~~~~~~~~~~~~``````")
number_1=(int(input("Enter your first number:")))
number_2=(int(input("Enter your second number:")))
print("the entered numbers are:",number_1,number_2)
print("addition of two numbers is:",number_1+number_2)
print("subtraction of two numbers is:",number_1-number_2)
print("multiplication of two numbers is:",number_1*number_2)
print("division of two numbers is:",number_1/number_2)