print("=======================")
print("Student Information")
print("=======================")
name=input("enter your name:")
print(name)
age=input("enter your age:")
print(age)
college=input("enter your college name:")
print(college)
branch=input("enter your branch:")
print(branch)
section=input("enter your section:")
print(section)